"""MANIFEST.md5 generator (`cc-fuzzer manifest write|check`).

MANIFEST.md5 is what scripts/integrity-check.sh compares the installed plugin
against: one `<md5>  <relative-path>` line per tracked file, `#` comments
allowed. It used to be hand-maintained and drifted; this module is now its
only writer (scripts/gen-manifest.sh is the shim).

Tracked: the core's shipped sources (TRACKED) plus whatever extra paths the
caller passes with --include (the plugin shim adds its host-adapter trees).
Deliberately NOT tracked:
  - rules/        externally sourced semgrep rule content, refreshed out of band
  - top-level docs, flake.nix, tests/, pyproject.toml
  - __pycache__/ and *.pyc
"""
from __future__ import annotations

import hashlib
import os
import sys
from pathlib import Path

# Relative paths (files or directories) whose files are always tracked.
TRACKED = (
    "STATE_SCHEMA.md",
    "bin",
    "dictionaries",
    "references",
    "scripts",
    "src/cc_fuzzer_core",
    "templates",
)

_SKIP_DIRS = {"__pycache__", ".git"}
_SKIP_SUFFIXES = (".pyc", ".pyo")

HEADER = """\
# cc-fuzzer plugin file manifest
# Generated by scripts/gen-manifest.sh (cc-fuzzer manifest write). Do not edit.
# Used by integrity-check.sh to detect drift.
# Format: <md5>  <relative-path>
#
# NOTE: rules/ (the bundled semgrep rule pack under rules/semgrep plus the
# rules/trailofbits submodule) is intentionally EXCLUDED from integrity
# tracking. Rule content is externally sourced and updated independently of
# plugin releases (the submodule tracks upstream; the bundled pack may be
# refreshed out of band), so drift there is expected and must not trip the
# integrity check. The SAST driver scripts/_lib/sast_scan.py IS tracked.
"""


def default_root() -> Path:
    """The tree to manifest: the plugin root (paths.plugin_root())."""
    from cc_fuzzer_core.paths import plugin_root
    return plugin_root()


def tracked_files(root: Path, include=()) -> list[str]:
    """Sorted relative paths of every tracked regular file under root.
    `include` adds extra relative paths (files or directories) to TRACKED."""
    out = []
    for rel in (*TRACKED, *include):
        p = root / rel
        if p.is_file():
            out.append(rel)
            continue
        if not p.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(p):
            dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRS)
            for fn in filenames:
                if fn.endswith(_SKIP_SUFFIXES):
                    continue
                full = Path(dirpath) / fn
                if full.is_file() and not full.is_symlink():
                    out.append(full.relative_to(root).as_posix())
    return sorted(set(out))


def md5_file(path: Path) -> str:
    h = hashlib.md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def render(root: Path, include=()) -> str:
    lines = [HEADER]
    for rel in tracked_files(root, include):
        lines.append(f"{md5_file(root / rel)}  {rel}\n")
    return "".join(lines)


def write(root: Path, output: Path | None = None, include=()) -> Path:
    """Regenerate the manifest atomically; return its path."""
    out = output or (root / "MANIFEST.md5")
    tmp = out.with_name(out.name + ".tmp")
    tmp.write_text(render(root, include))
    # The plugin's read-only lock (enforce-readonly.sh) may have chmod a-w'd the
    # old manifest; os.replace only needs the directory writable.
    os.replace(tmp, out)
    return out


def check(root: Path, manifest: Path | None = None, include=()) -> list[str]:
    """Drift lines ("MISSING: x", "MODIFIED: x", "UNTRACKED: x") vs the
    committed manifest. Empty list == in sync."""
    mf = manifest or (root / "MANIFEST.md5")
    expected = {}
    for line in mf.read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        digest, _, rel = line.partition("  ")
        expected[rel.strip()] = digest.strip()
    problems = []
    actual = tracked_files(root, include)
    for rel in actual:
        if rel not in expected:
            problems.append(f"UNTRACKED: {rel}")
        elif md5_file(root / rel) != expected[rel]:
            problems.append(f"MODIFIED: {rel}")
    for rel in sorted(set(expected) - set(actual)):
        problems.append(f"MISSING: {rel}")
    return problems


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cmd_write(args):
    root = Path(args.root) if args.root else default_root()
    out = write(root, Path(args.output) if args.output else None, args.include)
    print(out)
    return 0


def _cmd_check(args):
    root = Path(args.root) if args.root else default_root()
    problems = check(root, include=args.include)
    if not problems:
        print("ok")
        return 0
    for p in problems:
        print(p)
    return 1


def register_cli(subparsers):
    from cc_fuzzer_core.cli import add_subsystem

    _p, verbs = add_subsystem(subparsers, "manifest", "MANIFEST.md5 generation and drift check")
    w = verbs.add_parser("write", help="regenerate MANIFEST.md5")
    w.add_argument("--root", help="tree to manifest (default: plugin root)")
    w.add_argument("--output", help="write here instead of <root>/MANIFEST.md5")
    w.add_argument("--include", action="append", default=[], metavar="PATH",
                   help="extra relative path (file or dir) to track; repeatable")
    w.set_defaults(func=_cmd_write)
    c = verbs.add_parser("check", help="compare the tree against MANIFEST.md5 (exit 1 on drift)")
    c.add_argument("--root", help="tree to check (default: plugin root)")
    c.add_argument("--include", action="append", default=[], metavar="PATH",
                   help="extra relative path (file or dir) to track; repeatable")
    c.set_defaults(func=_cmd_check)

