#!/usr/bin/env bash
# build-symcc-target.sh
#
# Rebuilds the target with SymCC instrumentation, producing a parallel binary
# next to the regular fuzz harness. Reads the original build command from
# fuzz/state/harness-built.json and substitutes symcc/sym++ for clang/clang++.
#
# Output: fuzz/symcc/<harness-name>_symcc

set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/_lib/nix-tools.sh"

HARNESS_INFO="${FUZZ_STATE_DIR:-fuzz/state}/harness-built.json"

if [ ! -f "$HARNESS_INFO" ]; then
  echo "ERROR: $HARNESS_INFO not found. Run /cc-fuzzer:harness first." >&2
  exit 1
fi

# If inside the cc-fuzzer nix FHS shell and the harness was built with the nix
# backend, delegate the symcc variant build to nix-build.sh — it already knows
# how to drive sym++ inside the derivation sandbox.
if [ "${CC_FUZZER_FHS:-}" = "1" ]; then
  _NIX_BACKEND=$(python3 -c "
import json
try:
    d = json.load(open('$HARNESS_INFO'))
    print(d.get('build_backend', 'legacy'))
except Exception:
    print('legacy')
" 2>/dev/null || echo legacy)
  if [ "$_NIX_BACKEND" = "nix" ]; then
    _NIX_HARNESS=$(python3 -c "
import json
try:
    d = json.load(open('$HARNESS_INFO'))
    print(d.get('name', ''))
except Exception:
    print('')
" 2>/dev/null || echo "")
    if [ -n "$_NIX_HARNESS" ]; then
      echo "[build-symcc-target] nix backend detected — delegating to nix-build.sh --variant symcc" >&2
      exec bash "$SCRIPT_DIR/nix-build.sh" "$_NIX_HARNESS" --variant symcc
    fi
  fi
fi

# Resolve symcc and sym++ via nix-env.json (captured at session start) with
# PATH fallback. nix_require prints a fix-it diagnostic and exits 2 on miss.
SYMCC_BIN_TOOL=$(nix_require symcc)
SYMPP_BIN_TOOL=$(nix_require "sym++")
# Prepend the directory containing the resolved tools to PATH so the
# tokenizer substitution below finds the right binaries.
_SYMCC_DIR="$(dirname "$SYMCC_BIN_TOOL")"
if [[ ":$PATH:" != *":$_SYMCC_DIR:"* ]]; then
  export PATH="$_SYMCC_DIR:$PATH"
  echo "[symcc] prepended PATH with $_SYMCC_DIR" >&2
fi

# Extract the regular build command and harness path
BUILD_CMD=$(python3 -c "
import json
d = json.load(open('$HARNESS_INFO'))
print(d['build_command'])
")
HARNESS_BIN=$(python3 -c "
import json
d = json.load(open('$HARNESS_INFO'))
print(d['harness_binary'])
")

if [ -z "$BUILD_CMD" ] || [ -z "$HARNESS_BIN" ]; then
  echo "ERROR: could not read build_command or harness_binary from $HARNESS_INFO" >&2
  exit 1
fi

# Substitute compilers and output path. Keep all other flags except -fsanitize=fuzzer
# which SymCC does not understand. We replace it with a tiny libFuzzer-compatible
# main shim so the resulting binary reads stdin like a normal program.
SYMCC_BIN="fuzz/symcc/$(basename "$HARNESS_BIN")_symcc"
mkdir -p "$(dirname "$SYMCC_BIN")"

# Write the main shim that adapts LLVMFuzzerTestOneInput for SymCC's stdin model
SHIM=$(mktemp --suffix=.c)
cat > "$SHIM" <<'EOF'
/* SymCC main shim: feeds stdin to LLVMFuzzerTestOneInput.
 * Generated by cc-fuzzer build-symcc-target.sh */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

extern int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);

#ifdef __cplusplus
extern "C" {
#endif
__attribute__((weak)) int LLVMFuzzerInitialize(int *argc, char ***argv) { return 0; }
#ifdef __cplusplus
}
#endif

int main(int argc, char **argv) {
    LLVMFuzzerInitialize(&argc, &argv);
    /* SymCC drives input via stdin. Read up to 1 MiB. */
    static uint8_t buf[1024 * 1024];
    size_t n = fread(buf, 1, sizeof(buf), stdin);
    LLVMFuzzerTestOneInput(buf, n);
    return 0;
}
EOF

# Build the SymCC version. Strip libFuzzer and ASan/UBSan flags (SymCC's runtime
# is independent), add the shim, and use sym++ if the original used clang++.
SYMCC_CMD=$(echo "$BUILD_CMD" | python3 -c "
import sys, re, shlex
cmd = sys.stdin.read().strip()
# Tokenize and filter
toks = shlex.split(cmd)
out = []
skip_next = False
for i, t in enumerate(toks):
    if skip_next:
        skip_next = False
        continue
    # Drop sanitizer/fuzzer flags - SymCC doesn't compose with them
    if t.startswith('-fsanitize') or t == '-fno-omit-frame-pointer':
        continue
    # Substitute compiler
    if t == 'clang' or t.endswith('/clang'):
        out.append('symcc'); continue
    if t == 'clang++' or t.endswith('/clang++'):
        out.append('sym++'); continue
    # Substitute output path
    if t == '-o':
        out.append('-o'); skip_next = True
        out.append('$SYMCC_BIN'); continue
    out.append(t)
print(' '.join(shlex.quote(x) if x != '$SYMCC_BIN' else x for x in out))
")

# Append the shim source and link with -lpthread (SymCC runtime needs it)
SYMCC_CMD="$SYMCC_CMD $SHIM -lpthread"

echo "Building SymCC target..."
echo "  command: $SYMCC_CMD"
echo "  output:  $SYMCC_BIN"
echo ""

if eval "$SYMCC_CMD"; then
  rm -f "$SHIM"
  echo ""
  echo "SUCCESS. SymCC binary at $SYMCC_BIN"
  # Update harness-built.json with the symcc path
  python3 -c "
import json
d = json.load(open('$HARNESS_INFO'))
d['symcc_binary'] = '$SYMCC_BIN'
json.dump(d, open('$HARNESS_INFO', 'w'), indent=2)
"
  exit 0
else
  rm -f "$SHIM"
  echo ""
  echo "FAILED. SymCC build did not succeed." >&2
  echo "Common causes:" >&2
  echo "  - the regular build links against libraries SymCC's runtime conflicts with" >&2
  echo "  - target uses C++ exceptions (SymCC has limited exception support)" >&2
  echo "  - target uses inline asm (SymCC cannot symbolize inline asm)" >&2
  exit 1
fi
